### ISSUE TITLE
No glyph for the key character to derive standard width and height.

### ISSUE THREAD

**Issue by Arooj-Shahid** [fmalina/PDFtranscript#11]
I'm working with ubuntu 16.04 LTS and I ran those 2 commands present in your Readme i.e.  brew install python3 pdf2htmlEX and pip3 install -r requirements.txt and then configure Data_Path as well but when I run my file i.e. ./pdf2htmlpy ./transcript.py it keeps on saying
No glyph for the key character to derive standard width and height.
For the latin script, this key character is `o' (U+006F).
No glyph for the key character to derive standard width and height.
For the latin script, this key character is `o' (U+006F).
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
No glyph for the key character to derive standard width and height.
For the latin script, this key character is `o' (U+006F).
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
No glyph for the key character to derive standard width and height.
For the latin script, this key character is `o' (U+006F).
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning lookup 8 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
No glyph for the key character to derive standard width and height.
For the latin script, this key character is `o' (U+006F).
Lookup 'mark' Mark Positioning lookup 7 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Internal Error: assembly tables at wrong place
Working: 2/2
[None]

Is this font forge error and how to resolve this? as my HTML folder afterwards do contain my pdf converted htmls but without images and it doesn't parse my html, my HTM folder remains empty

my pdf2htmlEX version 0.14.6
Libraries: 
  poppler 0.41.0
  libfontforge 20120731
Default data-dir: /usr/share/pdf2htmlEX
Supported image format: png jpg
where am I wrong?

**Comment by fmalina** [comment]
Not clear enough.

**Comment by Arooj-Shahid** [comment]
Hi, @fmalina I'm working with ubuntu 16.04 LTS and I ran those 2 commands present in your Readme i.e. brew install python3 pdf2htmlEX and pip3 install -r requirements.txt and then configure Data_Path as well but when I run my file i.e. ./pdf2htmlpy ./transcript.py it keeps on saying

"No glyph for the key character to derive standard width and height.
For the latin script, this key character is o' (U+006F). No glyph for the key character to derive standard width and height. For the latin script, this key character iso' (U+006F).
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
No glyph for the key character to derive standard width and height.
For the latin script, this key character is o' (U+006F). Lookup 'mark' Mark Positioning in Arabic lookup 0 has an offset bigger than 65535 bytes. This means FontForge must use an extension lookup to output it. Not all applications support extension lookups. No glyph for the key character to derive standard width and height. For the latin script, this key character iso' (U+006F).
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning in Arabic lookup 0 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Lookup 'mark' Mark Positioning lookup 8 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
No glyph for the key character to derive standard width and height.
For the latin script, this key character is `o' (U+006F).
Lookup 'mark' Mark Positioning lookup 7 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Internal Error: assembly tables at wrong place
Working: 2/2
[None]"

Is this font forge error and how to resolve this? as my HTML folder afterwards do contain my pdf converted htmls but without images and it doesn't parse my html, my HTM folder remains empty

my pdf2htmlEX version 0.14.6
Libraries:
poppler 0.41.0
libfontforge 20120731
Default data-dir: /usr/share/pdf2htmlEX
Supported image format: png jpg

where am I wrong?
