### ISSUE TITLE
Cannot get any output.

### ISSUE THREAD

**Issue by cani-venatici** [fmalina/PDFtranscript#12]
Trying to configure `config.py` without success.

My pdf was generated by lualatex, and i can convert it to html using `pdf2htmlEX.exe`[°](https://github.com/coolwanglu/pdf2htmlEX), so i'd assume my pdf is not an issue. However i can't get this repo to work. I've tried converting other pdfs and the outcome is the same described here.

I've configured the `config.py` like so
`DATA_DIR = "/Users/Matteo Wakalaka/font-tools/transcript-data"`
`PDF_DIR  = DATA_DIR+'PDF'`
`HTML_DIR = DATA_DIR+'HTML'`
`FULL_FONTS_PATH  = "/Users/Matteo Wakalaka/font-tools/otf"`

I'm on windows so i can't use brew to install pdf2htmlEX. I installed it from here [°](http://soft.rubypdf.com/software/pdf2htmlex-windows-version) as linked from pdf2htmlEX download page, and added it and ttfautohint to the `path` in case it's needed for `transcript.py` or `pdf2html.py`. (?)

When i try to execute i get [this output](http://puu.sh/BUCmH/32da127af2.png) in the console, and empty folders `transcript-dataHTML` and `transcript-dataHTM` are generated.

**Comment by cani-venatici** [comment]
Based on someone else help i managed to fix it on windows. `pdf2html.py` assumes we're working under unix environment. So the paths were messing up.

What I did is:

1. Put pdf2htmlEX for windows [(from here)](http://soft.rubypdf.com/software/pdf2htmlex-windows-version) in a folder attached to my `path`;

2. _Copy_ `pdf2htmlEX.exe` and its `data` folder where `pdf2html.py` is; If you don't do this the script can't access pdf2htmlEX's `manifest` file in `pdf2htmlEX/data/manifest` for some reason and produces a 0kb html file.

3. Download `ttfautohint` [(from here)](https://www.freetype.org/ttfautohint/#download), as it's an argument of `pdf2htmlEX.exe`, and put that in my `path`;

4. Edit `pdf2html.py` line 13 like this: `fn = pdf_path.split('\\')[-1].replace('.pdf','')` only difference involves changing `split('/')` to `split('\\')`;

5. Create a folder called `stuff` on the same directory where `pdf2html.py` is;

6. Create a folder called `PDF` inside `stuff`;

7. Create a `fonts` folder inside `stuff` and put the fonts your pdf uses, there;

8. Edit path lines in `config.py` like so:
    `DATA_DIR = 'stuff/'`
    `PDF_DIR  = DATA_DIR+'PDF'`
    `HTML_DIR = DATA_DIR+'HTML'`
    `FULL_FONTS_PATH  = 'stuff/fonts'`

9. run `python3 .\pdf2html.py`, then `python3 .\transcript.py`

10. If you need to run `pdf2htmlEX.exe` with certain arguments edit `pdf2html.py` lines 16 through 20

**Comment by gednigel** [comment]
> Based on someone else help i managed to fix it on windows. `pdf2html.py` assumes we're working under unix environment. So the paths were messing up.
> 
> What I did is:
> 
> 1. Put pdf2htmlEX for windows [(from here)](http://soft.rubypdf.com/software/pdf2htmlex-windows-version) in a folder attached to my `path`;
> 2. _Copy_ `pdf2htmlEX.exe` and its `data` folder where `pdf2html.py` is; If you don't do this the script can't access pdf2htmlEX's `manifest` file in `pdf2htmlEX/data/manifest` for some reason and produces a 0kb html file.
> 3. Download `ttfautohint` [(from here)](https://www.freetype.org/ttfautohint/#download), as it's an argument of `pdf2htmlEX.exe`, and put that in my `path`;
> 4. Edit `pdf2html.py` line 13 like this: `fn = pdf_path.split('\\')[-1].replace('.pdf','')` only difference involves changing `split('/')` to `split('\\')`;
> 5. Create a folder called `stuff` on the same directory where `pdf2html.py` is;
> 6. Create a folder called `PDF` inside `stuff`;
> 7. Create a `fonts` folder inside `stuff` and put the fonts your pdf uses, there;
> 8. Edit path lines in `config.py` like so:
>    `DATA_DIR = 'stuff/'`
>    `PDF_DIR  = DATA_DIR+'PDF'`
>    `HTML_DIR = DATA_DIR+'HTML'`
>    `FULL_FONTS_PATH  = 'stuff/fonts'`
> 9. run `python3 .\pdf2html.py`, then `python3 .\transcript.py`
> 10. If you need to run `pdf2htmlEX.exe` with certain arguments edit `pdf2html.py` lines 16 through 20

Where do you download specified fonts files?

**Comment by cani-venatici** [comment]
> Where do you download specified fonts files?

You have to provide t
he script the fonts used for compiling the pdf. If you haven't designed the pdf and don't know which fonts have been used you can try see what are the embedded fonts and provide those if you own them.

Another option could be to export the pdf to a word file with acrobat pro and convert the word to html with pandoc. Both of these conversions will generate inaccurate layouts that will almost surely need tweaking, though.

**Comment by fmalina** [comment]
I fixed the top path issue on Windows you had and made use of paths more system independent, closing
