### ISSUE TITLE
Internal Error: assembly tables at wrong place

### ISSUE THREAD

**Issue by QGB** [fmalina/PDFtranscript#13]
@coolwanglu I'm working with the linux enviornment 16.04 LTS and I compiled my pdf2htmlEX from this site: https://github.com/fmalina/transcript
and ran this command: brew install python3 pdf2htmlEX but when i run my file it keeps saying 
No glyph for the key character to derive standard width and height.
For the latin script, this key character is `o' (U+006F).
Lookup 'mark' Mark Positioning lookup 7 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Internal Error: assembly tables at wrong place
Is this font forge error and how to resolve this?

_Originally posted by @AroojPerzada in https://github.com/coolwanglu/pdf2htmlEX/issues/333#issuecomment-270854344_

https://github.com/coolwanglu/pdf2htmlEX/issues/333#issuecomment-270854344

**Comment by fmalina** [comment]
I added support for use of Docker install image and this is the one I will support.

Install with `docker pull pdf2htmlex/pdf2htmlex:0.18.8.rc2-master-20200820-ubuntu-20.04-x86_64`
