### ISSUE TITLE
cssselect does not seem to be installed

### ISSUE THREAD

**Issue by AnhellO** [fmalina/PDFtranscript#2]
First of all, thanks for this complement for the pdf2htmlEX tool, is really cool, I've been playing a lot with the configs!

I wasn't sure about opening the issue, but maybe in the future somebody else can have this issue, so I think it would be a good thing to point out.

At first try, I just followed the README to do all the installation and configurations. After that, I was trying to execute the scripts, but then I had an issue while executing transcript.py. I didn't save the traceback logs, but [here is something](https://github.com/lxml/lxml/blob/master/src/lxml/cssselect.py#L16) related with this issue. Although there is a question on [StackOverflow](http://stackoverflow.com/questions/23221073/how-to-fix-issue-with-the-removed-cssselect-package-in-lxml) (not too much related), it is not a fancy thing to solve. Just installing cssselect with pip was enough to make the script works. I was thinking in send a pull with some contribution for that issue, by just modifying the README and the requirements, but I'm not sure enough about the way of contributing to the project.

Also, on the [lxml documentation](http://lxml.de/3.6/lxmldoc-3.6.0.pdf) (updated on March 17th) they mention the lxml.cssselect as an external module, so that is also maybe related to this.

**Comment by Balmung421** [comment]
Thanks for this, but I have a question for you: have you gotten this script to work? Currently trying to set it up, and I can't seem to get any results. I am confident it is user error on my end. As for your cssselect info, I made sure to install that as well, so thanks for that!

**Comment by AnhellO** [comment]
@Balmung421, so far now the script is working after installing the cssselect module, not as expected at the first try (the treated content doesn't look close to the pdf2html generated content and I'm not able to see the images after executing the transcript.py. Maybe I should tweak some code from the transcript script and play with it to make it work better), but processing the html from the pdf2html script. I have a doubt with the `FULL_FONTS_PATH`, not pretty sure what path to use in there. What about you?.  I'll keep looking at it.
