### ISSUE TITLE
How to use it with pdf2htmlex Debian package

### ISSUE THREAD

**Issue by mdmane** [fmalina/PDFtranscript#20]
how to use this if I have the pdf2htmlEX setup up and running that is Debian package on Ubuntu 22.04 please let me know as I am already converting pdf to html using pdf2htmlex and now further want to semanticize the html file as it has multiple spans and div tags to be eliminated and tables aren't generated in tr, td tags after my conversion from pdf2htmlex

**Comment by fmalina** [comment]
I added docs for how to install and run with the Debian package
