### ISSUE TITLE
Requires: pip install freetype-py - even though installed

### ISSUE THREAD

**Issue by twigbranch** [fmalina/PDFtranscript#4]
> $ ./transcript.py 
> Requires: pip install freetype-py
> Loading fonts from: /Users/f/SITES/etc/ttf
> $ pip install freetype-py
> Requirement already satisfied (use --upgrade to upgrade): freetype-py in /usr/local/lib/python2.7/site-packages
> $ pip install freetype-py --upgrade
> Requirement already up-to-date: freetype-py in /usr/local/lib/python2.7/site-packages

Any idea what could be going wrong here?

I'm using Mac OSX 10.11.5.  I followed the install instructions in the README.

**Comment by fmalina** [comment]
Use python3, not python2.7.

`pip3 install freetype-py`
