### ISSUE TITLE
Two issues: *_* file selection, manual creation of PDF, HTML, and HTM directories

### ISSUE THREAD

**Issue by twigbranch** [fmalina/PDFtranscript#5]
Issue 1: In the last line of pdf2html.py and transcript.py you select files based on "*_*" yet it's unclear (and unmentioned anywhere) why filenames must have the format *_*.  With this setting, pdf2html.py and transcript.py where not finding all pdf files in the PDF directory.  When I replaced "*_*" with simply "*" it did find the pdf files.

Issue 2: I may have missed it, but in the README it might help to clearly specify that PDF, HTML and HTM directories have to be manually created by the user.  But, it would seem better behavior that the script automatically create HTML and HTM directories if they don't exist, since the script is the only one that writes to those directories.

**Comment by fmalina** [comment]
All done. `transcript.py` had the same issue with ___ filenames. Test and let me know if you are happy with the changes. Saves time if you're at it anyway.
