### ISSUE TITLE
Recover text in sementicize

### ISSUE THREAD

**Issue by jacwah** [fmalina/PDFtranscript#9]
When reading the source code I came across this weird couple of lines in transcript.py:
```
    # recover text from embedded fonts with bad CMAPS if > 50% of characters are unicode PUA
    recover = pua_content(dom.text_content()) > 0.5
    if recover:
        print('Recovery needed, not now.')
        return
        recover_text(dom, os.path.dirname(doc_path))
```

There is a call to recover text there, but it is unreachable since there is a return statement right before it. What is the intended behaviour here? If "not now", when?

**Comment by fmalina** [comment]
Text recovery is disabled. Enable it if you wish by removing that return.
